site_name: Bacannot pipeline
repo_url: https://github.com/fmalmeida/bacannot
repo_name: fmalmeida/bacannot
extra_css:
  - stylesheets/extra.css
nav:
    - Home: index.md
    - Installation: installation.md
    - Quickstart: quickstart.md
    - Samplesheet: samplesheet.md
    - Outputs: outputs.md
    - Manual: manual.md
    - Selecting NF profiles: profiles.md
#    config
#    custom-db
theme:
  name: material
  palette:
    primary: teal
    accent: deep purple
  icon:
    repo: fontawesome/brands/github-alt
plugins:
  - git-revision-date
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde