name: docker pull (skeleton images)
# Pull images every 6 months to keep them active in dockerhub
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *'

jobs:
  push_dockerhub:
    name: Pull docker images
    runs-on: ubuntu-latest
    # Only run for the nf-core repo, for releases and merged PRs
    if: ${{ github.repository == 'fmalmeida/bacannot' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Pull Docker image from DockerHub (all)
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker pull fmalmeida/bacannot_main_tools
          docker pull fmalmeida/bacannot:kofamscan
          docker pull fmalmeida/bacannot:renv
          docker pull fmalmeida/bacannot:jbrowse
