name: Testing new PR with singularity
on:
  pull_request:
    branches: [ master, dev, develop ]
    types: [ ready_for_review, synchronize, reopened ]

jobs:
  run_nextflow:
    name: Run pipeline for the upcoming PR
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Check out pipeline code
        uses: actions/checkout@v2
      
      - name: Install Nextflow
        env:
          CAPSULE_LOG: none
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      
      - name: Install Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      
      - name: Clean environment
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      
      - name: Build bacannot database
        run: |
          nextflow run main.nf -profile singularity --get_dbs --output bacannot_dbs --max_cpus 2 --max_memory '6.GB' --max_time '6.h'

      - name: Run the pipeline
        run: |
          nextflow run main.nf -profile singularity,quicktest --bacannot_db bacannot_dbs
